[project]
name = "advisories-analysis"
version = "0.1.0"
description = "GHSA Advisory Analysis"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.5",
    "pandas>=2.3.1",
]
